Add movieID to toplist in DB
RokasGit/sep6API pull request #2
Opened 2023-04-19 12:56 UTC by JakubPlatzek

2023-04-19 16:30 UTC, RokasGit commented
add a method into the service to call this method, as well if there is any need for data validation do that as well.
https://github.com/RokasGit/sep6API/blob/main/src/v1/services/movieService.ts
Inside controller call service.
https://github.com/RokasGit/sep6API/blob/main/src/v1/controllers/movieController.ts
Add a route with required query or arguments.
https://github.com/RokasGit/sep6API/blob/main/src/v1/routes/movieRoutes.ts

**I believe it should be part of movie controller as it controls where movies are, but if you think this should be part of toplist controller do that.**

2023-04-19 16:31 UTC, RokasGit requested changes
**add a method into the service to call this method, as well if there is any need for data validation do that as well.**
https://github.com/RokasGit/sep6API/blob/main/src/v1/services/movieService.ts
**Inside controller call service.**
https://github.com/RokasGit/sep6API/blob/main/src/v1/controllers/movieController.ts
**Add a route with required query or arguments.**
https://github.com/RokasGit/sep6API/blob/main/src/v1/routes/movieRoutes.ts

**I believe it should be part of movie controller as it controls where movies are, but if you think this should be part of toplist controller do that.**

2023-04-20 11:30 UTC, RokasGit commented
toplist should have its own controller, router and service.

2023-04-22 12:55 UTC, RokasGit requested changes
Wrote some comments, TLDR: probably lets use classes rather than standalone functions, then change some names, and then make it use promises, it allows for easier chaining etc.

2023-04-22 12:55 UTC, RokasGit commented on src/database/toplist.ts
use promises, so that it would be possible to chain them later on.

2023-04-22 12:55 UTC, RokasGit commented on src/index.ts
good

2023-04-22 12:55 UTC, RokasGit commented on src/v1/controllers/toplistController.ts
maybe lets change it into the class, it will be easier to export the functions.

2023-04-22 12:55 UTC, RokasGit commented on src/v1/routes/toplistRoutes.ts
should we include it like that or maybe it would be better to receive it as body content? rather than the url.

2023-04-22 12:55 UTC, RokasGit commented on src/v1/services/toplistService.ts
seems fine just probably need to change it into class as well and then make it use promises.

2023-04-22 12:55 UTC, RokasGit commented on src/v1/controllers/toplistController.ts
maybe instead of the name response body variable name use something more like true/false, either way if you just return true or false I do not think you need to send a response.

2023-04-22 15:11 UTC, JakubPlatzek commented on src/v1/controllers/toplistController.ts
i think response should be sent either way. what if adding fails? shouldn't user be notified on the front-end? right now the toplist.ts returns true or false depending on if it succeedes or fails.

2023-04-24 10:56 UTC, RokasGit approved these changes
I guess it is fine for now.

2023-04-24 10:56 UTC, RokasGit commented on src/database/toplist.ts
probably will not work as you are importing knex from knex instead import { db } from ./../database/index, and calling db("Toplist").insert etc.

2023-04-24 10:56 UTC, merged

2023-04-24 12:54 UTC, JakubPlatzek commented on src/database/toplist.ts
Ah so just the reference is wrong? I think the statement itself should be still fine.